name: Validate

on:
  pull_request:
    paths:
      - clis.json

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate clis.json against schema
        run: |
          npm install -g ajv-cli
          ajv validate -s schema.json -d clis.json
